name = "Git Commit"
grammar = "git_commit"
path_suffixes = [
  # https://github.com/neovim/neovim/blob/master/runtime/lua/vim/filetype.lua
  "COMMIT_EDITMSG",
  "EDIT_DESCRIPTION",
  "MERGE_MSG",
  "NOTES_EDITMSG",
  "TAG_EDITMSG",
]
line_comments = ["#"]
brackets = [
  { start = "(", end = ")", close = true, newline = false },
  { start = "`", end = "`", close = true, newline = false },
  { start = "\"", end = "\"", close = true, newline = false },
  { start = "'", end = "'", close = true, newline = false },
  { start = "{", end = "}", close = true, newline = false },
  { start = "[", end = "]", close = true, newline = false },
]
